export const LOAD_ARTICLES_START = 'LOAD_ARTICLES_START';
export const LOAD_ARTICLES_COMPLETE = 'LOAD_ARTICLES_COMPLETE';
export const LOAD_COMMENTS_START = 'LOAD_COMMENTS_START';
export const LOAD_COMMENTS_COMPLETE = 'LOAD_COMMENTS_COMPLETE';
export const ADD_COMMENT_START = 'ADD_COMMENT_START';
export const ADD_COMMENT_COMPLETE = 'ADD_COMMENT_COMPLETE';
